color: lime
description: null
fieldLayouts:
  17f974cf-5fe7-43e2-90d8-357ff155b84e:
    cardThumbAlignment: end
    cardView:
      - type
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-19T20:49:31+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bdcb410a-3021-4b6b-81d8-aac1e5598503
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-19T20:49:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: acdcfd1c-89a2-4090-989d-17db6ad24060 # Icon
            handle: accordionIcon
            includeInCards: false
            instructions: null
            label: 'Accordion Icon'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f9be6c16-5bbb-4665-a5ff-700ceb2a9b09
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-19T20:49:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 9ceecee1-0248-4ae3-a12a-c90171e5f42f # Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 40b6a49e-a758-4175-ab21-93c9ec3b06f2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9cf48e4f-e4a8-4e1c-ac80-5c3648bd7907
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-27T16:51:48+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f6807d6f-6a06-4137-8317-a236cec446bd # Type Settings
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4f896689-4a8d-41c7-9e60-b4a6f7d96c73
            userCondition: null
            warning: null
            width: 100
        name: Type
        uid: 01b0799b-ad2d-400e-89c9-2d475c1edbb4
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-19T20:49:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5514a63a-0a23-42f9-9333-5576b0e95462 # Color Scheme
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: df8f7abd-b9c0-4c4f-89ca-40552b5dd13a
            userCondition: null
            warning: null
            width: 100
        name: Color
        uid: 09f067e7-d40d-4c01-b8ed-77f11089735a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-27T17:09:45+00:00'
            elementCondition: null
            heading: Padding
            type: craft\fieldlayoutelements\Heading
            uid: 7bffb498-836f-4fd1-abb2-c40882480179
            userCondition: null
          -
            dateAdded: '2025-08-27T18:31:20+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 53df91b5-e85f-4b0c-8669-222678840f22 # Padding
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 99d26b9e-c704-449d-b81e-93ea648554db
            userCondition: null
            warning: null
            width: 100
        name: Spacing
        uid: 5665eb8c-b474-4622-822d-572827bab73a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-19T20:49:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6b484609-7d28-4f55-990e-f5212885d922 # Custom ID
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6b2693a2-5320-4ff9-9a71-39923bb640a4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-19T20:49:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a78e7e89-26cf-4a0e-a36d-b48ca76d7ba5 # Custom Classes
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 72b0657e-2c04-4de0-a72f-b3339f88b4cc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-19T20:49:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ee64f702-a8f1-46ee-8dea-79f8ad82e25b # Custom Attributes
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a8e17217-022b-4f03-a375-0132a011f437
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-27T17:09:45+00:00'
            elementCondition: null
            heading: 'Display Settings'
            type: craft\fieldlayoutelements\Heading
            uid: dff181af-4241-4199-be7d-29569793ca41
            userCondition: null
          -
            dateAdded: '2025-08-27T18:31:34+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 99a21841-a7ac-4726-85bf-4628867cba30 # Display
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3c85bb2c-c28f-4f97-a551-33e5273c8ff4
            userCondition: null
            warning: null
            width: 100
        name: Advanced
        uid: f73475c3-86d7-4725-a271-92a21d9a0ab2
        userCondition: null
handle: accordion
hasTitleField: true
icon: null
name: Accordion
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: Accordion
titleTranslationKeyFormat: null
titleTranslationMethod: site
