color: green
description: null
fieldLayouts:
  4c4ddfa7-2465-4c23-9d7e-35445d849237:
    cardThumbAlignment: end
    cardView:
      - type
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-19T20:49:36+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 14b108f6-dc62-426a-8159-41ba171bb8cb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-19T20:49:36+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3aa14a6e-dabc-42ae-8954-e10f19c53441 # Accordions
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 85fecb8e-b887-48f6-a74a-128d09fc0b53
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 40a7763d-183c-46da-b909-039a124912e3
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-19T20:49:36+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: acdcfd1c-89a2-4090-989d-17db6ad24060 # Icon
            handle: accordionIcon
            includeInCards: false
            instructions: null
            label: 'Accordion Icon'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 253af7eb-b575-4782-98d2-d643dc6484c6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-19T20:49:36+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d7a280bb-af78-455c-9bd1-1fc2f7e4018d # OpenClosed
            handle: accordionStartState
            includeInCards: false
            instructions: null
            label: 'First Accordion Start State'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ad6ce1b9-2edf-46e0-9c09-60c4ecce4a9d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-19T20:49:36+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a2da31ae-7341-4dd1-b245-5ee55d44cbc2 # Yes No
            handle: accordionsAllowMultiple
            includeInCards: false
            instructions: null
            label: 'Allow Multiple Accordions To Be Open At Once?'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0c2b4dd7-95c9-49e6-a71e-e69e2a8a7e1a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-19T20:49:36+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: bae3f95d-8506-49cb-891a-048c975b11d4 # Heading Level
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 23531d2e-1589-47b4-b2ed-b8ed41e286ff
            userCondition: null
            warning: null
            width: 100
        name: 'Control Settings'
        uid: c4dc1d49-d40d-4e7a-8c39-963610b4e736
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-27T19:47:27+00:00'
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'The settings for this element are applied to each of the sub accordions in the set. They can be overridden in the individual accordions if needed.'
            type: craft\fieldlayoutelements\Tip
            uid: 946ccdcc-2c4b-48b1-aa7e-6039a2c4176f
            userCondition: null
          -
            dateAdded: '2025-05-19T20:49:36+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5514a63a-0a23-42f9-9333-5576b0e95462 # Color Scheme
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9b7d457a-bf24-447b-bbed-346ab8996846
            userCondition: null
            warning: null
            width: 100
        name: Color
        uid: ee63fcd6-9005-4407-aa02-373d523f5b74
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-27T19:47:27+00:00'
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'The settings for padding are applied as an override on all of the accordions in the set. They can be overridden in each accordion if needed. The margin settings are applied to the group as a whole.'
            type: craft\fieldlayoutelements\Tip
            uid: e7b7a5ab-d8ce-4558-9cb5-699a7bd52fe9
            userCondition: null
          -
            dateAdded: '2025-08-27T18:44:12+00:00'
            elementCondition: null
            heading: Padding
            type: craft\fieldlayoutelements\Heading
            uid: df14da5d-a0fe-45ff-b514-d775d4c9f197
            userCondition: null
          -
            dateAdded: '2025-08-27T18:44:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 53df91b5-e85f-4b0c-8669-222678840f22 # Padding
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9e651127-d64e-4b79-8fc5-9c98680b4bc8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-27T18:44:12+00:00'
            elementCondition: null
            heading: Margins
            type: craft\fieldlayoutelements\Heading
            uid: 8dd8ae7d-b241-41e9-a1a9-6c93349adb2e
            userCondition: null
          -
            dateAdded: '2025-08-27T18:44:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 59bbbfc4-509e-4f06-91c5-065e1688562e # Margins
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 99bda455-b931-4bd8-8e4b-08d5d78cb8f8
            userCondition: null
            warning: null
            width: 100
        name: Spacing
        uid: ff49a8e9-8b4d-4c9d-8f29-5d1cea0e71c6
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-19T20:49:36+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6b484609-7d28-4f55-990e-f5212885d922 # Custom ID
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 69c54b00-33bc-4e3b-8213-ded81d31ccf0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-19T20:49:36+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a78e7e89-26cf-4a0e-a36d-b48ca76d7ba5 # Custom Classes
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 99fb42cb-66a2-487a-896e-02ec202938e1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-19T20:49:36+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ee64f702-a8f1-46ee-8dea-79f8ad82e25b # Custom Attributes
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 56f41a82-33a4-49bb-9cb6-a5d0e061f438
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-27T18:44:12+00:00'
            elementCondition: null
            heading: 'Display Settings'
            type: craft\fieldlayoutelements\Heading
            uid: a44da34e-1fb5-4d4d-94fd-61547598a638
            userCondition: null
          -
            dateAdded: '2025-08-27T18:44:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 99a21841-a7ac-4726-85bf-4628867cba30 # Display
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6ea6ee61-a500-43a4-a19f-4c4e2202fb14
            userCondition: null
            warning: null
            width: 100
        name: Advanced
        uid: b3ea43d9-6cda-405b-9735-80ef906ab405
        userCondition: null
handle: accordionSet
hasTitleField: true
icon: null
name: 'Accordion Set'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: 'Accordion Set'
titleTranslationKeyFormat: null
titleTranslationMethod: site
