color: pink
description: null
fieldLayouts:
  5341d892-306b-451e-9db6-ac97fd0c598a:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-11-18T20:00:14+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: eaf22e5f-1786-41e9-bc4d-0a8682bab8af # Media Device Size
            handle: deviceSize
            includeInCards: false
            instructions: null
            label: 'Device Size'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4638fad0-cf1c-4b8e-a62e-c23ee16bc8a8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-18T20:00:14+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: bb89e543-0de1-4a53-9480-2e7c0e8a69a5 # Aspect Ratio
            handle: frameAspect
            includeInCards: true
            instructions: null
            label: 'Frame Aspect Ratio'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3858dc49-f36c-40f1-b46d-915f3dfee3c2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-18T20:00:14+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0fe2ca3f-eb30-4294-96a2-1154bd95e41e # Background Position
            handle: mediaPosition
            includeInCards: false
            instructions: null
            label: 'Media Positon'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 05012290-fe8b-440b-9bbc-c3227a694109
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 693c573d-20d0-42e6-af9c-feb0b74a1476
        userCondition: null
handle: artDirectionVideo
hasTitleField: false
icon: null
name: 'Art Direction - Video'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{object.owner.title}-ImageSource-{deviceSize}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
