color: yellow
fieldLayouts:
  bb944a46-5889-4b31-9c83-36e3783d2c5a:
    cardView:
      - type
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-05T21:12:17+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c7c46511-5e9a-4b9f-b624-2c34b9d4db0b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-23T20:05:43+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 66354233-a357-4d3f-9543-7f92fef4d662 # Card Content
            handle: excerpt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 87f1abb8-d7c5-47bb-a84f-782f4a6860b5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-05T21:12:17+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f1b466ce-fb41-471a-90d4-5d0fd23f346d # Image Asset
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3c1817e6-839c-4977-8d96-da534a4c0b42
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: fd013db0-29ce-4c76-b8d3-ec34466f2195
        userCondition: null
handle: contentCard
hasTitleField: true
icon: null
name: 'Content Card'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: 'Content Card'
titleTranslationKeyFormat: null
titleTranslationMethod: site
