color: lime
description: null
fieldLayouts:
  602761bd-0558-4ccc-9ed4-25035ccc88d3:
    cardThumbAlignment: end
    cardView:
      - type
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-19T20:49:52+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7dd38a2f-a68f-4f4f-af10-d2874e8aad21
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-19T20:49:52+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 9ceecee1-0248-4ae3-a12a-c90171e5f42f # Content
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ffa0fd04-151f-4094-a7d2-0a689296d2f5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a18837ef-f239-47ad-b80a-5ec134c43f02
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-27T19:00:17+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f6807d6f-6a06-4137-8317-a236cec446bd # Type Settings
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2c7295bf-19a2-4b29-81d2-25e5583067cf
            userCondition: null
            warning: null
            width: 100
        name: Type
        uid: c3e4c172-a24b-45fc-907e-c7f80789dbd7
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-27T19:00:17+00:00'
            elementCondition: null
            heading: Padding
            type: craft\fieldlayoutelements\Heading
            uid: 43c870fe-e9c2-4013-9b2d-527acccb9877
            userCondition: null
          -
            dateAdded: '2025-08-27T19:00:17+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 53df91b5-e85f-4b0c-8669-222678840f22 # Padding
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: caabff2b-613a-4d96-acba-15574282376c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-27T19:00:17+00:00'
            elementCondition: null
            heading: Margins
            type: craft\fieldlayoutelements\Heading
            uid: 66c8ce02-0091-43f9-8c28-20136f8256db
            userCondition: null
          -
            dateAdded: '2025-08-27T19:00:17+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 59bbbfc4-509e-4f06-91c5-065e1688562e # Margins
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7e616ff0-1385-433f-bf85-8b216a1566ab
            userCondition: null
            warning: null
            width: 100
        name: Spacing
        uid: 0a33214f-e704-44c6-a6ba-8781116fab48
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-19T20:49:52+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5514a63a-0a23-42f9-9333-5576b0e95462 # Color Scheme
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1e7cdb7b-5cd0-4749-9df8-b821e70a7e5e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-19T20:49:52+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 487ec441-2218-43e8-8a96-652a0649e437 # Color Picker
            handle: bgColor
            instructions: null
            label: 'Background Color'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4828bf4d-05a0-4a1c-a43b-4093be361a58
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-27T19:00:17+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 487ec441-2218-43e8-8a96-652a0649e437 # Color Picker
            handle: textColor
            instructions: null
            label: 'Text Color'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d72120c7-7a53-4104-b709-4e58cf0b22e0
            userCondition: null
            warning: null
            width: 100
        name: Color
        uid: b42c56c6-36d3-4ec4-9476-3e7154204af8
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-03T19:52:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 76e84206-fdd5-4553-bf04-6f24f458ce0e # Background Settings
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e094e219-aec0-422c-a05b-eca499d5831e
            userCondition: null
            warning: null
            width: 100
        name: Background
        uid: af16ebf4-513c-42d1-ae13-9a4193e30f78
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-19T20:49:52+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6b484609-7d28-4f55-990e-f5212885d922 # Custom ID
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d6e1e93-38ca-405d-a935-f5c62bdbbd8f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-19T20:49:52+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a78e7e89-26cf-4a0e-a36d-b48ca76d7ba5 # Custom Classes
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9d984080-00be-4234-a6a2-c62e0226bd6d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-19T20:49:52+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ee64f702-a8f1-46ee-8dea-79f8ad82e25b # Custom Attributes
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 70d72450-b609-4046-a6e7-d48fb9de6841
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-27T19:00:17+00:00'
            elementCondition: null
            heading: 'Display Settings'
            type: craft\fieldlayoutelements\Heading
            uid: 216b9dd7-6e53-41cb-9a55-f5c073836860
            userCondition: null
          -
            dateAdded: '2025-08-27T19:00:17+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 99a21841-a7ac-4726-85bf-4628867cba30 # Display
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 15bfdc68-62e7-4906-8140-446b9e3a1610
            userCondition: null
            warning: null
            width: 100
        name: Advanced
        uid: 3cc35afe-af1b-4ee8-aa89-d2d5c11e61b9
        userCondition: null
handle: contentWrapper
hasTitleField: true
icon: null
name: 'Content Wrapper'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: 'Content Wrapper'
titleTranslationKeyFormat: null
titleTranslationMethod: site
