allowLineBreaksInTitles: false
color: pink
description: null
fieldLayouts:
  9986dffe-a1af-42bd-aec4-8e3f7369ebfe:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:905b0cb4-d08b-42e7-8475-96bd0b2b02fc'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-01-30T21:03:49+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: b688f2ad-48f2-460c-ad2c-ad3dc97599ca # Device Size
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6c77f660-4048-47d6-a02d-df65a9ab0564
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-07T23:10:48+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 50cd7a70-a0fe-4d38-a86d-9358735fc84c # Hidden Visible
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 905b0cb4-d08b-42e7-8475-96bd0b2b02fc
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: b6afa78d-71ea-439f-bae4-4dface488000
        userCondition: null
    thumbFieldKey: null
handle: displayAdjustment
hasTitleField: false
icon: null
name: 'Display Adjustment'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{object.owner.title}-Display-{layoutSize}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
