color: yellow
description: null
fieldLayouts:
  05db9514-d611-48e5-aa08-85e2bfbfd7b2:
    cardThumbAlignment: end
    cardView:
      - type
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-19T20:50:08+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 98dc6e85-08cb-4409-9553-024ebd9883dd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-19T20:50:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f0c10f75-8d5e-43c0-83a1-2321c04a2ebd # Form to Display
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b70a6d37-506f-4fd9-92dd-500d4f7cef89
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-19T20:50:08+00:00'
            elementCondition: null
            heading: Button
            type: craft\fieldlayoutelements\Heading
            uid: 2a95d88e-e710-4127-88e6-ebe02ee57c5b
            userCondition: null
          -
            dateAdded: '2025-05-19T20:50:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 47acc143-9347-4976-bd50-02778ffeabf1 # Button Styles
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 74587eb4-c316-41d3-acd3-7289c4eb852f
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-05-19T20:50:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: adca13f3-4ae5-49c5-83c4-cab3dd9f5ece # Button Size
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2f3275b2-f0fa-4055-966f-f0ac23a07c7d
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-05-19T20:50:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 487ec441-2218-43e8-8a96-652a0649e437 # Color Picker
            handle: btnColor
            instructions: null
            label: 'Button Color'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2364078c-7f2a-419d-a6ac-c4151f6845ee
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 86886d72-23a0-4ed6-ad37-cdbf282f55ce
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-19T20:50:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5514a63a-0a23-42f9-9333-5576b0e95462 # Color Scheme
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ed35e7c-6939-46ea-b885-6b8a0d79b5b6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-19T20:50:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 487ec441-2218-43e8-8a96-652a0649e437 # Color Picker
            handle: bgColor
            instructions: 'Use this field to override the background color that is specified in the color scheme.'
            label: 'Background Color'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7e13abd3-b221-48b5-84ec-af9f273e6513
            userCondition: null
            warning: null
            width: 100
        name: Color
        uid: 28211a06-91fd-4664-90f6-6815239a56db
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-27T19:52:37+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 59bbbfc4-509e-4f06-91c5-065e1688562e # Margins
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c34a1de-037c-4ec6-9038-5865a1853b65
            userCondition: null
            warning: null
            width: 100
        name: Spacing
        uid: c5a77de5-eab1-4b62-9770-541619282cab
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-19T20:50:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6b484609-7d28-4f55-990e-f5212885d922 # Custom ID
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f2facd2d-d982-461c-a150-23d18e24bf5d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-19T20:50:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a78e7e89-26cf-4a0e-a36d-b48ca76d7ba5 # Custom Classes
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f00b5fda-2e1f-4cd3-9a3b-d2ab1324bdf2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-19T20:50:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ee64f702-a8f1-46ee-8dea-79f8ad82e25b # Custom Attributes
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5d16fba8-fa27-4abc-8bc6-79e1ea6b4184
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-27T19:52:37+00:00'
            elementCondition: null
            heading: 'Display Settings'
            type: craft\fieldlayoutelements\Heading
            uid: 5c3861ac-5a33-4def-9493-4cad6e2a66c8
            userCondition: null
          -
            dateAdded: '2025-08-27T19:52:37+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 99a21841-a7ac-4726-85bf-4628867cba30 # Display
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e0263ef8-ece6-44af-8372-89b189cc47d8
            userCondition: null
            warning: null
            width: 100
        name: Advanced
        uid: 3e7f673b-53b9-493a-a1d1-b289567774c1
        userCondition: null
handle: form
hasTitleField: true
icon: null
name: Form
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: Form
titleTranslationKeyFormat: null
titleTranslationMethod: site
