color: cyan
description: null
fieldLayouts:
  f3589bbe-232b-4610-91e0-458e9a97c5ef:
    cardThumbAlignment: end
    cardView:
      - type
      - 'layoutElement:999bdee3-ba97-4ca8-9fa4-f50e7a6bde8d'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-09T19:57:46+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b4c4f21e-35c3-40ba-b812-86a3bc213582 # Main Heading Text
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ea087174-926a-48ad-aaae-949002a192c7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-08T04:36:22+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: bae3f95d-8506-49cb-891a-048c975b11d4 # Heading Level
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 999bdee3-ba97-4ca8-9fa4-f50e7a6bde8d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-27T20:48:33+00:00'
            elementCondition: null
            heading: 'Type Styling'
            type: craft\fieldlayoutelements\Heading
            uid: 10f76587-42b9-4f0a-93af-417992196f2a
            userCondition: null
          -
            dateAdded: '2024-12-08T04:36:22+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: aeeead9c-f591-4d95-a990-f8bea54fb0ef # Heading Style
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e554bb46-5847-4596-ad6e-af34b33fd73c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-27T20:48:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f6807d6f-6a06-4137-8317-a236cec446bd # Type Settings
            handle: typeSettingsMainHeadline
            instructions: null
            label: 'Type Overrides - Main Headline'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3486fe31-5177-435d-aab6-676fca4aab7c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-27T20:48:33+00:00'
            elementCondition: null
            heading: Color
            type: craft\fieldlayoutelements\Heading
            uid: 35db9f79-9cd4-4e97-8eed-a0ffaa6a015b
            userCondition: null
          -
            dateAdded: '2024-12-08T04:36:22+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 487ec441-2218-43e8-8a96-652a0649e437 # Color Picker
            handle: headlineColor
            instructions: null
            label: 'Headline Color'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8bc08470-059f-42d0-8bda-5f0d65784b4d
            userCondition: null
            warning: null
            width: 100
        name: 'Main Headline'
        uid: a70d97af-159d-463f-ac71-a8066ef1f2c6
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-09T20:04:45+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e976e669-f3ac-496a-8450-9d5613262236 # Subhead Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 56c2ee74-82e7-455e-97cf-4bb500984096
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-08T04:36:22+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 77532772-badf-4ce5-a93b-6752273d81bb # Subhead Position
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 287f346b-8868-40e8-a7e0-408fa444e7c0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-08T04:36:22+00:00'
            elementCondition: null
            heading: 'Type Styling'
            type: craft\fieldlayoutelements\Heading
            uid: 0516af06-0a83-4846-890e-d08beb3e72fa
            userCondition: null
          -
            dateAdded: '2024-12-08T04:36:22+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\TextFieldConditionRule
                  fieldUid: 0f72b724-e0a8-4044-a3aa-12255ade6ea1 # Basic Text with Search
                  layoutElementUid: f1d6104a-7887-4f72-96a0-5e15a7d7852f
                  operator: notempty
                  uid: 75f97ee2-587b-4230-b172-a7345ea47514
                  value: ''
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: e5bff211-8719-442c-8ca7-caf236c14273 # Subhead Style
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 34775be6-9c0e-4d7c-964f-2f86afd255f8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-27T20:52:59+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 62336b23-c907-4179-a797-e2f7a8d75533 # Type Overrides - Subhead
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 68c3fd0b-6c56-40ea-8485-f75139a2a33c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-08T04:36:22+00:00'
            elementCondition: null
            heading: Color
            type: craft\fieldlayoutelements\Heading
            uid: 9df28174-ab49-4f7a-8b90-c7d9063797fb
            userCondition: null
          -
            dateAdded: '2024-12-08T04:36:22+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 487ec441-2218-43e8-8a96-652a0649e437 # Color Picker
            handle: subheadColor
            instructions: null
            label: 'Subhead Color'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 97b31351-cea6-44b5-a858-34fbb595aa4c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-27T20:52:59+00:00'
            elementCondition: null
            heading: Spacing
            type: craft\fieldlayoutelements\Heading
            uid: f3c51a34-ea6b-4891-8e73-39636473328f
            userCondition: null
          -
            dateAdded: '2025-08-27T20:52:59+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 91d05e51-ee38-4e73-af4c-ebed7e7572d3 # Spacing
            handle: subheadSpacing
            instructions: 'Use this field to override the default stylesheet spacing between the subhead and the main headline.'
            label: 'Subhead Spacing'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5e7b5d96-547a-4549-ae75-8505052037d4
            userCondition: null
            warning: null
            width: 100
        name: Subhead
        uid: 7bbb70b5-68f5-43d1-b90f-a4e04dd31342
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-27T20:48:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 59bbbfc4-509e-4f06-91c5-065e1688562e # Margins
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 67d7ad56-63db-405d-93ca-6ded5f1769eb
            userCondition: null
            warning: null
            width: 100
        name: Spacing
        uid: d8b76224-f909-4675-a9f3-2d6f9df01d42
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-08T04:36:22+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6b484609-7d28-4f55-990e-f5212885d922 # Custom ID
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8a32e6b7-91d7-40f3-8f96-1a6b5f985b1f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-08T04:36:22+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a78e7e89-26cf-4a0e-a36d-b48ca76d7ba5 # Custom Classes
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e53597c5-5b2c-4993-91ec-2e0350454682
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-08T04:36:22+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ee64f702-a8f1-46ee-8dea-79f8ad82e25b # Custom Attributes
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bf3824f1-d669-439a-b5d0-047c342cb20f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-27T20:48:33+00:00'
            elementCondition: null
            heading: 'Display Settings'
            type: craft\fieldlayoutelements\Heading
            uid: fce12334-ad92-419e-b4f1-7c250c790a08
            userCondition: null
          -
            dateAdded: '2025-08-27T20:48:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 99a21841-a7ac-4726-85bf-4628867cba30 # Display
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9650c1b1-1f38-47dc-a46d-23535b1d6e90
            userCondition: null
            warning: null
            width: 100
        name: Advanced
        uid: b4a609f4-ddc5-4065-83d4-7b8b3f98bd77
        userCondition: null
handle: heading
hasTitleField: false
icon: helicopter-symbol
name: Heading
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: Heading
titleTranslationKeyFormat: null
titleTranslationMethod: site
