color: pink
description: null
fieldLayouts:
  e63995f4-64f7-4377-a4ff-f88d54cb649e:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:ca6c7457-0ecb-40c0-bb25-f2b31e17e5ec'
      - 'layoutElement:97db9ffc-f10a-4e06-9513-f2883b5f0dc4'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-20T22:32:11+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7f182d27-ea6e-4a71-a3f8-5c9d0f147eed # Layout Size
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 832cc504-549f-4e54-bbd7-c0c48f154afd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-20T22:16:59+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 049ec87b-57e9-4b3e-8d53-44cb8874474b # Width
            handle: null
            instructions: null
            label: 'Frame Width'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca6c7457-0ecb-40c0-bb25-f2b31e17e5ec
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-09-20T22:16:59+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: bb89e543-0de1-4a53-9480-2e7c0e8a69a5 # Aspect Ratio
            handle: frameAspect
            instructions: null
            label: 'Frame Aspect Ratio'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 97db9ffc-f10a-4e06-9513-f2883b5f0dc4
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-09-17T19:38:39+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0fe2ca3f-eb30-4294-96a2-1154bd95e41e # Background Position
            handle: imagePosition
            instructions: null
            label: 'Image Position'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6b19dc92-61bf-42b0-9db1-0e2bb08ae827
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 6c2995dc-4eab-4967-a632-caae41ee1561
        userCondition: null
handle: imageArtDirectionFrameAdjustment
hasTitleField: false
icon: null
name: 'Image Art Direction Adjustment - Frame'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{object.owner.title}-{layoutSize}-ArtDirection-Frame'
titleTranslationKeyFormat: null
titleTranslationMethod: site
