allowLineBreaksInTitles: false
color: pink
description: null
fieldLayouts:
  1331e924-b13a-4d73-83e5-3b0d682fdeb5:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:baa745ef-7ac5-43c3-821e-cb670ca04f00'
      - 'layoutElement:81437c9c-e54a-4f5a-8feb-6c80feeed144'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-11-18T19:08:13+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: eaf22e5f-1786-41e9-bc4d-0a8682bab8af # Media Device Size
            handle: deviceSize
            instructions: null
            label: 'Device Size'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6ace2b64-74ff-4822-8f23-f7686a12c799
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-20T22:30:13+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f1b466ce-fb41-471a-90d4-5d0fd23f346d # Image Asset
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: baa745ef-7ac5-43c3-821e-cb670ca04f00
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-20T22:30:13+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: bb89e543-0de1-4a53-9480-2e7c0e8a69a5 # Aspect Ratio
            handle: mediaAspect
            instructions: null
            label: 'Media Aspect Ratio'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 81437c9c-e54a-4f5a-8feb-6c80feeed144
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-18T19:08:13+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 0fe2ca3f-eb30-4294-96a2-1154bd95e41e # Background Position
            handle: mediaPosition
            instructions: null
            label: 'Media Position'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a5a9d649-8947-4609-bf34-44c4f8a701d6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 382488e6-a998-4297-a9e5-ca63aa7a6d18
        userCondition: null
    thumbFieldKey: 'layoutElement:baa745ef-7ac5-43c3-821e-cb670ca04f00'
handle: imageSource
hasTitleField: false
icon: null
name: 'Image Art Direction - Image'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{object.owner.title}-ImageSource-{deviceSize}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
