color: pink
description: null
fieldLayouts:
  8134a302-a941-441b-b16e-d91fa2c1e84b:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:cccc0d55-4e21-483f-9d5d-b22853f420ba'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-27T21:53:42+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7f182d27-ea6e-4a71-a3f8-5c9d0f147eed # Layout Size
            handle: null
            instructions: null
            label: 'Layout Size'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d337f1d9-a04b-46a5-90a0-b519d257fff1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-27T21:53:42+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 049ec87b-57e9-4b3e-8d53-44cb8874474b # Width
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cccc0d55-4e21-483f-9d5d-b22853f420ba
            userCondition: null
            warning: null
            width: 50
        name: Settings
        uid: 836e1293-54cb-4f61-b252-05ce4f75cd04
        userCondition: null
handle: imageSizeAdjustment
hasTitleField: false
icon: null
name: 'Image Size Adjustment'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{object.owner.title}-Size-{layoutSize}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
