color: pink
description: null
fieldLayouts:
  cb7267dc-730a-43ac-bee9-1c0b2b7b9b78:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:e0e05a0e-c2eb-41b9-8880-1471296ad1ee'
      - 'layoutElement:84903f95-ce19-4ec9-adcf-d21a772456d0'
      - 'layoutElement:440f0a90-71d8-43c3-b304-3faba70343e5'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-11-18T20:57:18+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b688f2ad-48f2-460c-ad2c-ad3dc97599ca # Device Size
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 734df158-1c84-4dd4-a222-8f4574b581d1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-28T18:13:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 29a6be8e-cb85-466e-a2f5-a9b2a388d92a # Horizontal Alignment
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e0e05a0e-c2eb-41b9-8880-1471296ad1ee
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-28T18:13:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 413dfe3a-277c-4fba-a7ed-27de63a9a93f # Vertical Alignment
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 84903f95-ce19-4ec9-adcf-d21a772456d0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-12T21:29:16+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 91d05e51-ee38-4e73-af4c-ebed7e7572d3 # Spacing
            handle: gutterSize
            includeInCards: true
            instructions: null
            label: 'Gutter Size'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 440f0a90-71d8-43c3-b304-3faba70343e5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7e0ca690-dd67-404d-8077-f6e587b8686e
        userCondition: null
handle: layoutAdjustment
hasTitleField: false
icon: null
name: 'Layout Adjustment'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{object.owner.title}-layout-{layoutSize}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
