color: pink
description: null
fieldLayouts:
  cb7267dc-730a-43ac-bee9-1c0b2b7b9b78:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:84903f95-ce19-4ec9-adcf-d21a772456d0'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-11-18T20:57:18+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b688f2ad-48f2-460c-ad2c-ad3dc97599ca # Device Size
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 734df158-1c84-4dd4-a222-8f4574b581d1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-28T18:13:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 413dfe3a-277c-4fba-a7ed-27de63a9a93f # Vertical Alignment
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 84903f95-ce19-4ec9-adcf-d21a772456d0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-19T17:09:20+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 91d05e51-ee38-4e73-af4c-ebed7e7572d3 # Spacing
            handle: gutterSize
            instructions: null
            label: 'Gutter Size'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9863b479-d949-42ac-9c0a-57aa6a6430aa
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7e0ca690-dd67-404d-8077-f6e587b8686e
        userCondition: null
handle: layoutAdjustment
hasTitleField: false
icon: null
name: 'Layout Adjustment'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{object.owner.title}-layout-{layoutSize}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
