allowLineBreaksInTitles: false
color: cyan
description: null
fieldLayouts:
  262b0049-b5f8-4ffd-8dcc-4347b71a3e63:
    cardThumbAlignment: end
    cardView:
      - type
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-19T20:51:03+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d289c527-3796-4c67-8e6e-0901f48e6c75
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-19T20:51:03+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 3fa40ffc-bcf8-4f2f-9462-19c808265175 # Multiline Text With Search
            handle: quoteText
            instructions: null
            label: 'Quote Text'
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b43a0aa2-8efc-4ced-a5cb-df0a63461fab
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-19T20:51:03+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 0f72b724-e0a8-4044-a3aa-12255ade6ea1 # Basic Text with Search
            handle: quoteCredit
            instructions: null
            label: 'Quote Credit'
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 63c65c89-4d71-4c46-a919-848ceaa003bb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-19T20:51:03+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 0f72b724-e0a8-4044-a3aa-12255ade6ea1 # Basic Text with Search
            handle: quoteCreditTitle
            instructions: null
            label: 'Quote Credit Title'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8a1bbb51-1624-4c62-8ef0-c29d1594afdd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 82a9237b-4304-4f34-8718-d8e92243f686
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-27T22:38:52+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f6807d6f-6a06-4137-8317-a236cec446bd # Type Settings
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8576041e-635c-42bb-b5c4-7f70f08d7499
            userCondition: null
            warning: null
            width: 100
        name: Type
        uid: 9176cf9e-5f66-4634-bdc6-9eab05c29fd7
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-02-05T18:14:38+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 59bbbfc4-509e-4f06-91c5-065e1688562e # Margins
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: de4619b0-de67-4111-98a3-e8f1b2daaa32
            userCondition: null
            warning: null
            width: 100
        name: Spacing
        uid: 6e7eb4ef-4455-488d-859e-76aa4b9d0f60
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-19T20:51:03+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 487ec441-2218-43e8-8a96-652a0649e437 # Color Picker
            handle: quoteColor
            instructions: null
            label: 'Quote Text Color'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 497b3737-5e4d-4b66-b998-3e6a46e619f1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-19T20:51:03+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 487ec441-2218-43e8-8a96-652a0649e437 # Color Picker
            handle: creditColor
            instructions: null
            label: 'Quote Credit Color'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2edb9745-5d7e-48b6-a6be-7990b9b2217f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-27T22:38:52+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 487ec441-2218-43e8-8a96-652a0649e437 # Color Picker
            handle: quoteCreditTitleColor
            instructions: null
            label: 'Quote Credit Title Color'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c10e2631-c74e-46f8-9934-1b4c437fe070
            userCondition: null
            warning: null
            width: 100
        name: Color
        uid: ec51c722-f780-477a-a65a-dcfcb50c16a3
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-19T20:51:03+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6b484609-7d28-4f55-990e-f5212885d922 # Custom ID
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e5d14ba1-05de-4d86-b984-61e260ca4c73
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-19T20:51:03+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a78e7e89-26cf-4a0e-a36d-b48ca76d7ba5 # Custom Classes
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3345bae5-aaa1-458b-acfa-b6b719df499d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-19T20:51:03+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: ee64f702-a8f1-46ee-8dea-79f8ad82e25b # Custom Attributes
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 20b2bc22-c831-4239-a60e-0ecfd559d2c9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-27T22:38:52+00:00'
            elementCondition: null
            heading: 'Display Settings'
            type: craft\fieldlayoutelements\Heading
            uid: f2fe8419-e205-4f4d-9972-556755f2cea9
            userCondition: null
          -
            dateAdded: '2025-08-27T22:38:52+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 99a21841-a7ac-4726-85bf-4628867cba30 # Display
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 981e6c06-6945-461f-84de-dcf786b33a0d
            userCondition: null
            warning: null
            width: 100
        name: Advanced
        uid: ae8a600c-89ec-4dbc-a08f-7a8eeccfac99
        userCondition: null
    thumbFieldKey: null
handle: quote
hasTitleField: true
icon: null
name: Quote
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: Quote
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
