color: lime
description: null
fieldLayouts:
  052893b7-f328-4ef7-b529-33ce9c2515d1:
    cardThumbAlignment: end
    cardView:
      - type
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-04T22:07:15+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8d23cf78-5b01-4d12-9e85-90deb340eebd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-04T22:17:23+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 58342a22-c0c8-4901-8615-20d4d69694bb # Module to Include
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 28f2e091-c50b-486a-b6b0-aa09b5728e1e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: db5b2e5b-c1fb-466f-a466-0aeaaef0bb81
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-28T16:31:21+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f6807d6f-6a06-4137-8317-a236cec446bd # Type Settings
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f901aba7-1b5e-49a5-a5df-a2374215f31e
            userCondition: null
            warning: null
            width: 100
        name: Type
        uid: b9d1dfef-e807-49a2-8ef1-b2ce9e9b6fca
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-28T16:31:21+00:00'
            elementCondition: null
            heading: Padding
            type: craft\fieldlayoutelements\Heading
            uid: 1f47b49e-462a-4b6e-b174-a1386ce89140
            userCondition: null
          -
            dateAdded: '2025-08-28T16:31:21+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 53df91b5-e85f-4b0c-8669-222678840f22 # Padding
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c2977e4c-4149-43a1-ae9a-96d1cb4b0c52
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-28T16:31:21+00:00'
            elementCondition: null
            heading: Margins
            type: craft\fieldlayoutelements\Heading
            uid: bad03430-dd2e-4ac6-a796-09f7c7af3a00
            userCondition: null
          -
            dateAdded: '2025-08-28T16:31:21+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 59bbbfc4-509e-4f06-91c5-065e1688562e # Margins
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f30fed90-c0f2-4df0-89e6-2446223fc6bd
            userCondition: null
            warning: null
            width: 100
        name: 'Layout & Spacing'
        uid: 361ad53b-5c42-4842-8f2a-04a004763c01
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-04T22:15:56+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5514a63a-0a23-42f9-9333-5576b0e95462 # Color Scheme
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e36d5499-f26a-4864-8cfd-9a3dba909b37
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-04T22:15:56+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 487ec441-2218-43e8-8a96-652a0649e437 # Color Picker
            handle: bgColor
            instructions: null
            label: 'Background Color'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 03018ee8-ad19-4ecb-9185-eac5e441b7f2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-28T16:31:21+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 487ec441-2218-43e8-8a96-652a0649e437 # Color Picker
            handle: textColor
            instructions: null
            label: 'Text Color'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 710dc9ed-0869-4cbc-b7ac-7421a1e16eba
            userCondition: null
            warning: null
            width: 100
        name: Color
        uid: 5b69ce74-05bd-4a19-9ffd-39f6d6f3748c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-03T20:34:39+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 76e84206-fdd5-4553-bf04-6f24f458ce0e # Background Settings
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9eae3cb3-c028-4d1a-a5fd-2f9c49d8237c
            userCondition: null
            warning: null
            width: 100
        name: Background
        uid: 9a751baf-53d2-4490-a10d-78860b43344d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-04T22:15:56+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6b484609-7d28-4f55-990e-f5212885d922 # Custom ID
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f66593b6-59e5-4409-85ad-4644277521e0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-04T22:15:56+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a78e7e89-26cf-4a0e-a36d-b48ca76d7ba5 # Custom Classes
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4ebe8558-cfcb-4054-afe6-47af19ccca59
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-04T22:15:56+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ee64f702-a8f1-46ee-8dea-79f8ad82e25b # Custom Attributes
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2f9be7c3-728b-4c03-a85c-94e27a0c58f8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-28T16:31:21+00:00'
            elementCondition: null
            heading: 'Display Settings'
            type: craft\fieldlayoutelements\Heading
            uid: 9ebaaeac-23a5-46b8-ae2d-5bb4966b3de5
            userCondition: null
          -
            dateAdded: '2025-08-28T16:31:21+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 99a21841-a7ac-4726-85bf-4628867cba30 # Display
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f54a536d-d931-4936-a5e2-bff5bced0c57
            userCondition: null
            warning: null
            width: 100
        name: Advanced
        uid: c7751b9a-75cf-4690-a0a3-f68145487d9a
        userCondition: null
handle: reusableModuleWrapperSection
hasTitleField: true
icon: null
name: 'Reusable Module Wrapper Section'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: 'Reusable Module Section'
titleTranslationKeyFormat: null
titleTranslationMethod: site
