color: lime
description: null
fieldLayouts:
  8e0b7593-10b1-4c4c-bb45-45678f2b5cd2:
    cardThumbAlignment: end
    cardView:
      - type
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-20T20:14:02+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cc0ca11c-390d-435b-b3e6-aefee68fb132
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-20T20:14:02+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 9ceecee1-0248-4ae3-a12a-c90171e5f42f # Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dad94ce8-3508-4e54-9e50-e513ddc4aa61
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 24f3a0aa-3613-423f-8e2b-e4ae439cf922
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-28T16:50:32+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f6807d6f-6a06-4137-8317-a236cec446bd # Type Settings
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e1319e67-4634-445c-8a61-14b920897f9f
            userCondition: null
            warning: null
            width: 100
        name: Type
        uid: 686df012-ad01-4e4d-acf3-ddf26bd3d2f5
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-28T16:50:32+00:00'
            elementCondition: null
            heading: Padding
            type: craft\fieldlayoutelements\Heading
            uid: 3669f7f3-b1b2-4279-95e0-e4cfe313a7cb
            userCondition: null
          -
            dateAdded: '2025-08-28T16:50:32+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 53df91b5-e85f-4b0c-8669-222678840f22 # Padding
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8bf6e3a8-1fe3-4d41-a44a-32c8bb6ba479
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-28T16:50:32+00:00'
            elementCondition: null
            heading: Margins
            type: craft\fieldlayoutelements\Heading
            uid: d52a068a-1cee-462c-b945-b2817b16a8bc
            userCondition: null
          -
            dateAdded: '2025-08-28T16:50:32+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 59bbbfc4-509e-4f06-91c5-065e1688562e # Margins
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3b57f091-fbd6-4afb-b7bc-a2745a9b62e5
            userCondition: null
            warning: null
            width: 100
        name: 'Layout & Spacing'
        uid: 7449823c-aaae-475d-9661-5deb322f5f4f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-08-20T20:14:02+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5514a63a-0a23-42f9-9333-5576b0e95462 # Color Scheme
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cc950807-a3d5-43f6-9798-92be0edfef12
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-20T20:14:02+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 487ec441-2218-43e8-8a96-652a0649e437 # Color Picker
            handle: bgColor
            includeInCards: false
            instructions: null
            label: 'Background Color'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 94d60eb6-d57b-4a0a-b34c-15cb2e3cf84b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-28T16:50:32+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 487ec441-2218-43e8-8a96-652a0649e437 # Color Picker
            handle: textColor
            includeInCards: false
            instructions: null
            label: 'Text Color'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cfeb1d9e-daf1-4b6d-bf7f-2a8fdaa10304
            userCondition: null
            warning: null
            width: 100
        name: Color
        uid: 77da9b51-8b4c-493b-88fb-ce41b30264d6
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-03T20:36:47+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 76e84206-fdd5-4553-bf04-6f24f458ce0e # Background Settings
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a506188a-a403-459d-a452-6a114a28cfe9
            userCondition: null
            warning: null
            width: 100
        name: Background
        uid: 0ff3e389-7360-4cc8-b351-7e8f9eed87f8
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-08-20T20:14:02+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a2da31ae-7341-4dd1-b245-5ee55d44cbc2 # Yes No
            handle: animate
            includeInCards: false
            instructions: 'Activate this switch to animate the reveal of the section.'
            label: 'Animate Reveal?'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: caa28ec8-82dd-4af4-bf36-cb0ffc42883d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-20T20:14:02+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: a2da31ae-7341-4dd1-b245-5ee55d44cbc2 # Yes No
                  layoutElementUid: caa28ec8-82dd-4af4-bf36-cb0ffc42883d
                  uid: cd30a28a-6774-4b25-ae8a-6edbf3f8494a
                  value: true
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: a2da31ae-7341-4dd1-b245-5ee55d44cbc2 # Yes No
            handle: animateContent
            includeInCards: false
            instructions: 'Activate this switch if you want to animate the content of the section, but leave the background in place.'
            label: 'Animate Content Only'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5c10d250-4f45-4e85-8253-5aeb84ac0de9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-20T20:14:02+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: a2da31ae-7341-4dd1-b245-5ee55d44cbc2 # Yes No
                  layoutElementUid: 5c10d250-4f45-4e85-8253-5aeb84ac0de9
                  uid: 03cf43a7-fffe-4c4b-85c5-c6783c9fc53b
                  value: true
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: e3f9e59c-e941-404e-8bc8-b4c57ff28d5c # YesNo - Yes
            handle: staggerAnimations
            includeInCards: false
            instructions: 'Activate this switch if you want to have the content animations stagger.'
            label: 'Stagger Content Animations?'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1ce3569f-24a6-4334-abe6-3cc7b406e8ed
            userCondition: null
            warning: null
            width: 100
        name: Animation
        uid: b7b07ed8-f5cc-4c71-9cb8-7cb6382b7774
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-08-20T20:14:02+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6b484609-7d28-4f55-990e-f5212885d922 # Custom ID
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5630917c-85c1-4109-a096-527212072556
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-20T20:14:02+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a78e7e89-26cf-4a0e-a36d-b48ca76d7ba5 # Custom Classes
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b890854b-d3c1-4b56-a483-93c6405c6d64
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-20T20:14:02+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ee64f702-a8f1-46ee-8dea-79f8ad82e25b # Custom Attributes
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d8a204f6-7dc3-42fa-aa11-d4d86bb6cbf4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-28T16:50:32+00:00'
            elementCondition: null
            heading: 'Display Settings'
            type: craft\fieldlayoutelements\Heading
            uid: 08eff1c4-d280-4438-a6f6-737f936381c4
            userCondition: null
          -
            dateAdded: '2025-08-28T16:50:32+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 99a21841-a7ac-4726-85bf-4628867cba30 # Display
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7605137d-1b97-4d3d-b6c9-d4c3e8ed9170
            userCondition: null
            warning: null
            width: 100
        name: Advanced
        uid: 01de6442-98bd-40cb-ade1-f631cacf8722
        userCondition: null
handle: sectionStandard
hasTitleField: true
icon: null
name: Section
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: Section
titleTranslationKeyFormat: null
titleTranslationMethod: site
