color: lime
description: null
fieldLayouts:
  b30c8d55-fa5e-4ab5-aa70-56049d798dc9:
    cardThumbAlignment: end
    cardView:
      - type
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-19T20:52:01+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: dccc82e3-f36f-44d2-96ea-8f8d11714b1f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-19T20:52:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d897b42d-3d26-4db5-b105-29c871b31ffb # Limited Content
            handle: slideContent
            instructions: null
            label: 'Slide Content'
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fbc05a53-f8b5-45d8-b0bf-ac56150226a7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-19T20:52:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f1b466ce-fb41-471a-90d4-5d0fd23f346d # Image Asset
            handle: slideImage
            instructions: null
            label: 'Slide Image'
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a00f8583-ac8e-4e4d-991b-c88094be404b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-29T20:11:43+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f1b466ce-fb41-471a-90d4-5d0fd23f346d # Image Asset
            handle: slideImageSm
            instructions: 'Use this field to substitute a different image on small layouts that works better with the aspect ratio being use in small layouts. If the main Slide Image works at both sizes, you can leave this field empty.'
            label: 'Slide Image - Small Layouts'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3aced777-619c-4cc8-906d-3a1d4f97ebee
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e6a5ca0a-ca9b-4d27-b6f9-c330151d7750
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-19T20:52:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 24664393-bbfc-46d1-baab-46bef56260a7 # Slide Timing Override
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ebd85c81-d874-49a5-a35f-cb05b5a0d50a
            userCondition: null
            warning: null
            width: 100
        name: Controls
        uid: ec7a8b7a-41c7-4dd8-b12b-6979299756d2
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-28T17:04:39+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f6807d6f-6a06-4137-8317-a236cec446bd # Type Settings
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fe754e74-49cd-4df4-a56d-a05917ca696a
            userCondition: null
            warning: null
            width: 100
        name: Type
        uid: 26d46fe3-5f96-4912-bc08-6156d80e057b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-19T20:52:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5947f640-92a3-49d6-adfa-45816ba49d25 # Slide Horizontal Layout
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e0af11a3-efb7-474f-8f46-e65abb124326
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-05-19T20:52:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8977ed51-c96b-4f56-acf0-7b95d3182220 # Slide Vertical Layout
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: acd3f467-430d-44a3-8a35-d0b53b458168
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-08-28T17:04:39+00:00'
            elementCondition: null
            heading: Padding
            type: craft\fieldlayoutelements\Heading
            uid: 2e5b741c-9991-49f2-aa28-217c020c7deb
            userCondition: null
          -
            dateAdded: '2025-08-28T17:04:39+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 53df91b5-e85f-4b0c-8669-222678840f22 # Padding
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 96bdc631-797c-425e-bc07-6c5af4d0910e
            userCondition: null
            warning: null
            width: 100
        name: 'Layout & Spacing'
        uid: b1e6df55-fe38-4df8-af0b-c4b6e8088b5b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-19T20:52:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5514a63a-0a23-42f9-9333-5576b0e95462 # Color Scheme
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c6f3b387-c4dd-4eb7-b721-77a29d1dfa42
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-19T20:52:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 487ec441-2218-43e8-8a96-652a0649e437 # Color Picker
            handle: bgColor
            instructions: null
            label: 'Background Color'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e45dd5c1-f79c-45d5-997f-6aaa7a717219
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-28T17:04:39+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 487ec441-2218-43e8-8a96-652a0649e437 # Color Picker
            handle: textColor
            instructions: null
            label: 'Text Color'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d3f1ed87-1013-4823-93e4-1098971cffaf
            userCondition: null
            warning: null
            width: 100
        name: Color
        uid: cd3e099d-906c-4f82-b38f-b89f41065fe2
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-19T20:52:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6b484609-7d28-4f55-990e-f5212885d922 # Custom ID
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 886fd8c2-97fe-4aec-b469-1bdc77cc024a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-19T20:52:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a78e7e89-26cf-4a0e-a36d-b48ca76d7ba5 # Custom Classes
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 19266eee-1c43-4f1d-8631-d40db8587fb3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-19T20:52:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ee64f702-a8f1-46ee-8dea-79f8ad82e25b # Custom Attributes
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bc533033-b281-4d6e-bb39-a36c20717ed2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-29T20:46:58+00:00'
            elementCondition: null
            heading: Performance
            type: craft\fieldlayoutelements\Heading
            uid: 775fe47a-5ce2-442f-87e6-6e581f554d5c
            userCondition: null
          -
            dateAdded: '2025-09-29T20:46:58+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e3f9e59c-e941-404e-8bc8-b4c57ff28d5c # YesNo - Yes
            handle: lazyLoadImg
            instructions: 'When this switch is activated the image will not load until it is about to appear in the browser. If turned off, the image will load when the page loads. You should only turn this off if an image is going to appear at the top of a page.'
            label: 'Lazy Load Image'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 827085c5-ae1f-4861-a7f2-730c2f74561b
            userCondition: null
            warning: null
            width: 100
        name: Advanced
        uid: ec58402c-ca14-4d84-ba0e-cec3787663a8
        userCondition: null
handle: slide
hasTitleField: true
icon: null
name: Slide
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: Slide
titleTranslationKeyFormat: null
titleTranslationMethod: site
