color: green
description: null
fieldLayouts:
  aa0c56fc-31e5-40f7-a90d-57074a3dd470:
    cardThumbAlignment: end
    cardView:
      - type
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-19T20:52:08+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: da83b732-3ba7-495f-b524-66ba63f91649
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-19T20:52:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 40a37d8a-41c1-47af-bc27-28d08f99a909 # Slides
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bea5098d-f6e5-4987-99ea-87a754a36229
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f4a40c97-6fc7-424a-85a9-b230be5bf6f0
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-19T20:52:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: bb89e543-0de1-4a53-9480-2e7c0e8a69a5 # Aspect Ratio
            handle: slidePhotoSizeSm
            instructions: 'This control overrides the default slider photo aspect ratio for small layout sizes'
            label: 'Slide Photo Size-Small'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7b674c5b-4761-41ca-b22b-2775c8d7ee61
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-19T20:52:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: bb89e543-0de1-4a53-9480-2e7c0e8a69a5 # Aspect Ratio
            handle: slidePhotoSizeLg
            instructions: 'This control overrides the default slider photo aspect ratio for large layout sizes'
            label: 'Slide Photo Size-Large'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ced9f785-8511-499a-9e38-84767b59c5d1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-19T20:52:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5ad5f513-b34c-48ac-80bf-b573ed1e1f78 # On Off
            handle: buttons
            instructions: null
            label: 'Slider Control Buttons?'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b6f1f2da-6ee9-4135-9c21-fef154dd8e0c
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-05-19T20:52:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5ad5f513-b34c-48ac-80bf-b573ed1e1f78 # On Off
            handle: dots
            instructions: null
            label: 'Control Dots?'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f7453ad8-cbf8-4d90-b201-cec4739f38ce
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-05-19T20:52:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d1c26bcb-25db-404d-ba73-7e4e3c7fc0a1 # Slide Transition Delay
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1efd91ae-d148-4130-b4ef-d67548d1f903
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-05-19T20:52:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 53829185-3375-470c-80cf-a50b1733a8c4 # Slide Effect
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5993ed95-9983-43be-a3b2-ef7798ab43d9
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-05-19T20:52:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a2da31ae-7341-4dd1-b245-5ee55d44cbc2 # Yes No
            handle: autoplay
            instructions: null
            label: 'Autoplay?'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6bafac26-bac6-46f2-9cb6-705443971464
            userCondition: null
            warning: null
            width: 100
        name: 'Control Settings'
        uid: 1191b7e0-3d1d-4af0-ad44-2b3e68012618
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-28T17:06:39+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 59bbbfc4-509e-4f06-91c5-065e1688562e # Margins
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fc313360-e5bf-4c99-91af-0eecc4e99d57
            userCondition: null
            warning: null
            width: 100
        name: Spacing
        uid: 972f7741-9233-4209-9115-266a69db000a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-19T20:52:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5514a63a-0a23-42f9-9333-5576b0e95462 # Color Scheme
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 10028daf-64e6-48f9-a239-32318d57acd8
            userCondition: null
            warning: null
            width: 100
        name: Color
        uid: 5759cff1-b617-4af3-979c-3c3743f1ecb9
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-19T20:52:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6b484609-7d28-4f55-990e-f5212885d922 # Custom ID
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e8b773c0-6213-46c5-9c9b-13a0415b8e1e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-19T20:52:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a78e7e89-26cf-4a0e-a36d-b48ca76d7ba5 # Custom Classes
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5687f895-c83a-42ef-9e0f-f25b3118d253
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-19T20:52:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ee64f702-a8f1-46ee-8dea-79f8ad82e25b # Custom Attributes
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 763973ee-3273-4300-b8c1-4f8d9792cdfd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-28T17:06:39+00:00'
            elementCondition: null
            heading: 'Display Settings'
            type: craft\fieldlayoutelements\Heading
            uid: 4e874ed4-b371-45b3-8e39-6893960c7392
            userCondition: null
          -
            dateAdded: '2025-08-28T17:06:39+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 99a21841-a7ac-4726-85bf-4628867cba30 # Display
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2fec0727-6b65-4d28-93d7-e473f6e01f59
            userCondition: null
            warning: null
            width: 100
        name: Advanced
        uid: 1eeda2c0-8bb4-4edf-9f93-7c2a80a96ad3
        userCondition: null
handle: sliderSet
hasTitleField: true
icon: null
name: 'Slider Set'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: 'Slider Set'
titleTranslationKeyFormat: null
titleTranslationMethod: site
