columnSuffix: null
handle: margins
instructions: null
name: Margins
searchable: false
settings:
  fieldLayouts:
    __assoc__:
      -
        - 8ef66d5d-b445-443a-8285-7f27d4a744bc
        -
          __assoc__:
            0:
              - tabs
              -
                -
                  __assoc__:
                    1:
                      - uid
                      - ea858fff-df90-4a5e-a3e8-bb5739e49041
                    4:
                      - elements
                      -
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            1:
                              - handle
                              - mt
                            2:
                              - label
                              - 'Top Margin'
                            6:
                              - required
                              - false
                            7:
                              - providesThumbs
                              - false
                            8:
                              - includeInCards
                              - false
                            9:
                              - width
                              - 50
                            10:
                              - dateAdded
                              - '2025-11-18T22:25:17+00:00'
                            11:
                              - uid
                              - 95360aa7-e77b-4a84-b0f4-d3586eb2db19
                            14:
                              - fieldUid
                              - 4306ce1c-1d03-4d40-b285-d1f1f7ea0361 # Spacing - Margins
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            1:
                              - handle
                              - mb
                            2:
                              - label
                              - 'Bottom Margin'
                            6:
                              - required
                              - false
                            7:
                              - providesThumbs
                              - false
                            8:
                              - includeInCards
                              - false
                            9:
                              - width
                              - 50
                            10:
                              - dateAdded
                              - '2025-11-18T22:25:17+00:00'
                            11:
                              - uid
                              - 8f5235e6-297d-4549-9580-d09ac6cca279
                            14:
                              - fieldUid
                              - 4306ce1c-1d03-4d40-b285-d1f1f7ea0361 # Spacing - Margins
            3:
              - cardThumbAlignment
              - end
  viewMode: grouped
translationKeyFormat: null
translationMethod: site
type: craft\fields\ContentBlock
