columnSuffix: null
handle: mediaDeviceSize
instructions: null
name: 'Media Device Size'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - 'X-Small (320px and Above)'
        -
          - value
          - xs
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Small (Phone Horizontal and Above)'
        -
          - value
          - sm
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Medium (Tablet and Above)'
        -
          - value
          - md
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Large (Laptop and Above)'
        -
          - value
          - lg
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'X-Large (Desktop and Above)'
        -
          - value
          - xl
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '2XL (Hi-Res Display)'
        -
          - value
          - 2xl
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
