columnSuffix: null
handle: mediaType
instructions: null
name: 'Media Type'
searchable: false
settings:
  default: false
  offLabel: Photo
  onLabel: Video
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
